# Site settings
title: pkuzn's Page
email: pkuzn.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My blog where I post about stuff I made.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pkuzn.github.io" # the base hostname & protocol for your site
github_username:  pkuzn

# Build settings
markdown: kramdown
highlighter: false
